name: Build Firmware
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    # if: "github.event_name != 'pull_request' || contains(toJSON(github.event.pull_request.body), '[enable firmware ci]') || contains(toJSON(github.event.pull_request.labels.*.name), '[enable firmware ci]')"
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:v0.25.1
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: mycode

    - name: Install west
      run: |
        pip3 install -U wes
        west init -l .
        west update
        pip3 install -r ../zephyr/scripts/requirements-base.txt

    - name: Build multicore
      working-directory: mycode
      run: |
        west build --build-dir multicore\build multicore {{ matrix.sample }} --pristine \
        --board nrf5340dk_nrf5340_cpuapp -- -DNCS_TOOLCHAIN_VERSION:STRING="NONE" \
        -DCONF_FILE:STRING="multicore/prj.conf"
